# content of: tox.ini , put in same dir as setup.py
[tox]
skipsdist = True
envlist = py313

[testenv]
# install pytest in the virtualenv where commands will be executed
deps = 
    pytest
    -r{toxinidir}/requirements.txt
; changedir = tests
commands =
    # NOTE: you can run any command line tool here - not just tests
    python -m pytest -vv --durations=10 test/unit_test
